locale: en-US
encoding: UTF-8
url: https://mirrors.slickstack.io
repository: littlebizzy/slickstack
title: SlickStack Mirrors
description: SlickStack is a free LEMP stack automation script written in Bash designed to enhance and simplify FOSS CMS provisioning, performance, and security.
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
